<a href="https://colab.research.google.com/github/sivaroshan2007/Data-Analysis-Projects/blob/main/Task_1(Synent_Tech).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Load the latest version by specifying the target file name
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "yasserh/titanic-dataset",
  "Titanic-Dataset.csv"
)

print(df.head())

/tmp/ipykernel_1818/4260213037.py:5: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'titanic-dataset' dataset.
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
for i in df.columns:
    if df[i].isna().any():
        print(i)

Age
Cabin
Embarked

Fixing the missing values in age

In [ ]:
df['Age'] = df.groupby('Pclass')['Age'].transform(lambda x: x.fillna(x.median()))
# using the method of grouped median

In [ ]:
for i in df.columns:
    if df[i].isna().any():
        print(i)

Cabin
Embarked

Fixing the missing values in Embarked

In [ ]:
# Find the most common port
most_common_port = df['Embarked'].mode()[0]

# Fill the missing values
df['Embarked'] = df['Embarked'].fillna(most_common_port)

In [ ]:
for i in df.columns:
    if df[i].isna().any():
        print(i)

Cabin

Fixing the missing values in Cabin

In [ ]:
# Replace missing cabins with 'Unknown'
df['Cabin'] = df['Cabin'].fillna('Unknown')

In [ ]:
for i in df.columns:
    if df[i].isna().any():
        print(i)

Handling Duplicate Values

In [ ]:
duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 0

Converting Data Types

In [ ]:
# Convert Sex to 0 and 1
df['Sex'] = df['Sex'].map({'male': 1, 'female': 0})

In [ ]:
df['Sex'].dtypes

dtype('int64')

Using One hot coding concept for Embarked Column

In [ ]:
# Convert Embarked into multiple dummy columns (Embarked_Q, Embarked_S, etc.)
df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [ ]:
df['PassengerId'].dtype

dtype('int64')

 Convert PassengerId to string text To avoid Confusion

In [ ]:
# Convert PassengerId to string text
df['PassengerId'] = df['PassengerId'].astype(str)

In [ ]:
# Convert Pclass to a categorical type
df['Pclass'] = df['Pclass'].astype('category')

In [ ]:
df['Age'] = df['Age'].astype(int)

In [ ]:
print(df.dtypes)

PassengerId      object
Survived          int64
Pclass         category
Name             object
Sex               int64
Age               int64
SibSp             int64
Parch             int64
Ticket           object
Fare            float64
Cabin            object
Embarked_Q         bool
Embarked_S         bool
dtype: object

Enhancing the data for analysis

In [ ]:
# Rename columns for clarity and consistency
df = df.rename(columns={
    'Pclass': 'Passenger_Class',
    'SibSp': 'Siblings_Spouses',
    'Parch': 'Parents_Children',
    'Embarked_Q': 'Embarked_Queenstown',
    'Embarked_S': 'Embarked_Southampton'
})

#  Force all column names to lowercase for easier typing
df.columns = df.columns.str.lower()

In [ ]:
# Droping columns that won't be used in mathematical analysis
columns_to_drop = ['passengerid', 'name', 'ticket', 'cabin']
df = df.drop(columns=columns_to_drop, errors='ignore')

In [ ]:
# Combine columns to create 'family_size'
df['family_size'] = df['siblings_spouses'] + df['parents_children'] + 1  # (+1 includes the passenger themselves)

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   survived              891 non-null    int64
 1   passenger_class       891 non-null    category
 2   sex                   891 non-null    int64
 3   age                   891 non-null    int64
 4   siblings_spouses      891 non-null    int64
 5   parents_children      891 non-null    int64
 6   fare                  891 non-null    float64
 7   embarked_queenstown   891 non-null    bool
 8   embarked_southampton  891 non-null    bool
 9   family_size           891 non-null    int64
dtypes: bool(2), category(1), float64(1), int64(6)
memory usage: 51.6 KB
None

Data set is Ready For analysis